### ISSUE TITLE
Style spaces

### ISSUE THREAD

**Issue by AdriVanHoudt** [cheesypoof/QuickDark#2]
I see you added styling for tabs, to keep things consistent can you also add stylin for spaces?

**Comment by cheesypoof** [comment]
CodeMirror does not create HTML elements for spaces by default, so they cannot be styled without some additional JS. The [Show Whitespace](https://github.com/DennisKehrig/brackets-show-whitespace) extension might be of interest to you.

With that said, even though I personally prefer being able to distinguish between spaces and tabs, perhaps I should not have styled tabs at all... Some people will really dislike the arrows (or any alternative style) and as such, this should ideally be handled by an extension (not necessarily a theme). The tab arrows will probably be removed later this week unless I am persuaded otherwise.

**Comment by AdriVanHoudt** [comment]
Idd, I think this functionality belongs to a separate plugin
